version: "3"
services:
  pemweb:
    build: ./php
    image: pemweb_php:latest
    container_name: contohuts
    #hostname: "project-akhir"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  nginx:
    build: ./nginx
    image: nginx_pemweb:latest
    container_name: nginx
    #hostname: "nginx_pemweb"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pemweb

  database:
    image: mariadb:10.2
    container_name: databasecontohuts
    restart: unless-stopped
    tty: true
    ports:
      - "33306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql